// apps/react-app/src/exported-widgets/react-app-card/index.tsx
import {
  IonButton,
  IonCard,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonIcon,
} from "@ionic/react";
import { closeOutline, logoReact } from "ionicons/icons";
import { AtlasStyles } from "../../atlas-styles";

export interface ReactAppCardWidgetProps {
  subtitle?: string;
  /** Provided by the host when the widget renders inside a modal. */
  close?: () => void;
}

export default function ReactAppCardWidget({
  subtitle,
  close,
}: ReactAppCardWidgetProps) {
  return (
    <div className="p-4">
      <AtlasStyles />
      <IonCard className="m-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-md">
        <IonCardHeader className="flex flex-row items-start gap-4 px-5 pt-5 pb-3">
          <div className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-sky-100 text-sky-600">
            <IonIcon icon={logoReact} className="text-3xl" />
          </div>
          <div className="min-w-0 flex-1">
            <IonCardSubtitle className="text-xs font-semibold tracking-widest text-sky-600 uppercase">
              React widget
            </IonCardSubtitle>
            <IonCardTitle className="mt-1 text-xl font-bold text-slate-900">
              React App Card
            </IonCardTitle>
          </div>
          {close && (
            <IonButton
              fill="clear"
              color="medium"
              shape="round"
              size="small"
              aria-label="Close"
              className="m-0"
              onClick={() => close()}
            >
              <IonIcon slot="icon-only" icon={closeOutline} />
            </IonButton>
          )}
        </IonCardHeader>
        <div className="px-5 pt-1 pb-5">
          {subtitle && (
            <p className="text-sm leading-relaxed text-slate-600">{subtitle}</p>
          )}
          {close && (
            <IonButton
              expand="block"
              className="m-0 mt-5"
              onClick={() => close()}
            >
              Close
            </IonButton>
          )}
        </div>
      </IonCard>
    </div>
  );
}

// apps/angular-app/src/exported-widgets/angular-app-card/index.ts
import { Component, input } from "@angular/core";
import {
  IonButton,
  IonCard,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonIcon,
} from "@ionic/angular/standalone";
import { addIcons } from "ionicons";
import { closeOutline, logoAngular } from "ionicons/icons";

@Component({
  selector: "atlas-angular-app-card-widget",
  standalone: true,
  imports: [
    IonButton,
    IonCard,
    IonCardHeader,
    IonCardSubtitle,
    IonCardTitle,
    IonIcon,
  ],
  template: `
    <div class="p-4">
      <ion-card
        class="m-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-md"
      >
        <ion-card-header class="flex flex-row items-start gap-4 px-5 pt-5 pb-3">
          <div
            class="flex size-12 shrink-0 items-center justify-center rounded-xl bg-rose-100 text-rose-600"
          >
            <ion-icon name="logo-angular" class="text-3xl" />
          </div>
          <div class="min-w-0 flex-1">
            <ion-card-subtitle
              class="text-xs font-semibold tracking-widest text-rose-600 uppercase"
            >
              Angular widget
            </ion-card-subtitle>
            <ion-card-title class="mt-1 text-xl font-bold text-slate-900">
              Angular App Card
            </ion-card-title>
          </div>
          @if (close(); as close) {
            <ion-button
              fill="clear"
              color="medium"
              shape="round"
              size="small"
              aria-label="Close"
              class="m-0"
              (click)="close()"
            >
              <ion-icon slot="icon-only" name="close-outline" />
            </ion-button>
          }
        </ion-card-header>
        <div class="px-5 pt-1 pb-5">
          @if (subtitle()) {
            <p class="text-sm leading-relaxed text-slate-600">
              {{ subtitle() }}
            </p>
          }
          @if (close(); as close) {
            <ion-button expand="block" class="m-0 mt-5" (click)="close()">
              Close
            </ion-button>
          }
        </div>
      </ion-card>
    </div>
  `,
})
export default class AngularAppCardWidget {
  readonly subtitle = input("Angular App Card");
  readonly close = input<() => void>();

  constructor() {
    addIcons({ closeOutline, logoAngular });
  }
}
